version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    env_file: .env
    container_name: ${DISTRO_NAME}-build
    #command: /distro/src/build_dist
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
    devices:
      - /dev/loop-control
